name: API Call
on: 
  workflow_dispatch
jobs: 
  apiCall:
   runs-on: ubuntu-latest

   steps:
     - name: Package Creation
       id: new
       run: |
           
             data="[{
                        "a": "n"
                      }, {
                        "l": "k"
                      }]"

              show=$(echo ${data} | jq '.[]')
              echo $show
