name: API Call
on:
  workflow_dispatch
jobs: 
  apiCall:
   runs-on: ubuntu-latest
   steps:
     - name: Package Creation
       run: |
          curl --request POST \
          --header 'authorization: Basic dHJhaW5pbmdhc2htaXRhc2F3YW50LUQ5UDhKNy5ZRzFGQTQ6OWJmZDM5NWUtMzYxZC00MWFkLTgxMDctMTU0ZjU5Mzg0MDJm','accept: application/json' \
          --header 'content-type: application/json' \
          --url https://c01-sg.integrate.boomi.com/ws/rest/personDetails/v1/personDetails/
          --data '{\
                  "name":"Ashmita",\
                  "age":18,\
                  "role":"Software Engineer"\
                  }'
