name: API Call
on:
  workflow_dispatch
jobs: 
  apiCall:
   runs-on: ubuntu-latest
   steps:
     - name: Package Creation
       id: packageCreation
       uses: fjogeleit/http-request-action@master
       with:
        url: 'https://api.boomi.com/api/rest/v1/trainingashmitasawant-D9P8J7/PackagedComponent'
        method: 'POST'
        contentType: 'application/json'
        customHeaders: '{"accept": "application/json"}'
        data: '{"componentId": ${{needs.getProcessIds.outputs.output1}},"packageVersion":"p1", "notes":"Package for deployment" }'
        username: ${{env.MY_USERNAME}}
        password: ${{env.MY_PASSWORD}} 
     - run: |
            status= $(echo ${{ toJSON(steps.packageDeploy.outputs.status)
