name: API Call
on: 
  workflow_dispatch
jobs: 
  apiCall:
   runs-on: ubuntu-latest

   steps:
     - name: Package Creation
       id: new
       run: |
           
             data="{
              "cruises": [
                {

                  "waypoint_cities": [
                    "Palma de Mallorca",
                    "Cádiz",
                    "Puerto del Rosario, Fuerteventura",
                    "Arrecife, Lanzarote",
                    "Arrecife, Lanzarote",
                    "Agadir",
                    "Gibraltar",
                    "Barcelona",
                    "Palma de Mallorca"
                  ]}]}"
                  
              show=$(echo ${data} | jq '.[][][][0, -1]')
              echo $show
