name: Fetch Name

# Controls when the workflow will run
on:
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getName:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Process Info
        uses: actions/checkout@v2
      - id: getName
        run: |
             
                        file= $ echo |jq '. + [{"key2": "value2"}]'
                        echo $file >> out.json
                               git config user.name ashmitasawant
                               git config user.email ashmitasawant3@gmail.com
                               git add .
                               git commit -m "Published Changes"
                               git config pull.rebase false
                               git push --force origin main
