name: Fetch Name

# Controls when the workflow will run
on:
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getName:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Process Info
        uses: actions/checkout@v2
      - id: getName
        run: |
                nameget=$(cat ./packages.json)
                name=$(echo ${nameget} | jq '.{} | .environmentName')
                echo nameget
                echo name
