name: publish
on: [workflow_dispatch, repository_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Hii" >> published.txt
          git config user.name ashmitasawant
          git config user.email ashmitasawant3@gmail.com
          git add .
          git commit -m "Published Changes"
          git push
     
      - name: Get ComponentId
        uses: actions/checkout@v2
        id: setComponentId
      - run: |
            processDetails=$(cat ./ProcessInfo/processDetails.json)
            packageVersion=$(echo  ${ProcessDetails} | jq '.info[].packageVersion')
            componentId=$(echo  ${ProcessDetails} | jq '.[0].processDetails.componentID')
            environmentId=$(echo  ${ProcessDetails} | jq '.[0].processDetails.environmentID')
            echo $processDetails
            echo $packageVersion
            echo $componentId
            echo $environmentId
            
