name: Rollback Deployment

# Controls when the workflow will run
on:
  push:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createPackage:
    # The type of runner that the job will run on
    environment: Dev
    env: 
     MY_AUTHORIZATION: ${{ secrets.MY_AUTHORIZATION }}
    runs-on: ubuntu-latest
    outputs:
     packageId: ${{ steps.packageCreate.outputs.packageIds }}
     componentId: ${{steps.packageCreate.outputs.componentIds}}
     componentVersion: ${{steps.packageCreate.outputs.componentVersions}}
    
   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Create Package
        uses: actions/checkout@v2
      - id: packageCreate
        run: |
              CODE=`curl  --request POST \
                               --header 'authorization: ${{env.MY_AUTHORIZATION}}' \
                               --header 'content-type: application/json' \
                               --header 'accept: application/json' \
                               --url 'https://api.boomi.com/api/rest/v1/trainingashmitasawant-D9P8J7/PackagedComponent' \
                               --data '{"componentId": "aafd5e29-e75d-4bdb-9ec9-5b94ffd024d4","packageVersion":"v1.10", "notes":"Initial Package" }'`
                               echo $CODE
                               
                               packageIds=$(echo ${CODE} | jq '.packageId')
                               componentIds=$(echo ${CODE} | jq '.componentId')
                               componentVersion=$(echo ${CODE} | jq '.componentVersion')
                               
                               echo "::set-output name=packageIds::$packageIds"
                               echo "::set-output name=componentIds::$componentIds"
                               echo "::set-output name=componentVersions::$componentVersion"
               
  getInfo:
   runs-on: ubuntu-latest
   needs: createPackage
   steps:
     - name: Getting Information 
       run: echo "::set-output name=jsonCreated::${{steps.settingInfo.outputs.*,'\n'}}

     - id: settingInfo
       uses: jsdaniell/create-json@1.1.2
       with:
        name: "details.json"
        json: '{ "packageId": "${{needs.createPackage.outputs.packageId}}","componentId": "${{needs.createPackage.outputs.componentId}}","componentVersion": "${{needs.createPackage.outputs.componentVersion}}}'
      
