name: Deployment Pipeline

# Controls when the workflow will run
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getProcessInfo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.setProcessInfo.outputs.componentID }}
      output2: ${{ steps.setProcessInfo.outputs.environmentID }}
      output3: ${{ steps.setProcessInfo.outputs.packageVersion }}
      output4: ${{ steps.setProcessInfo.outputs.componentID_Array }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Process Info
        uses: actions/checkout@v2
      - id: setProcessInfo
        run: |
            ProcessDetails=$(cat ./ProcessInfo/ProcessDetails.json)
            packageVersion=$(echo  ${ProcessDetails} | jq '.[] | .packageVersion')
            componentID=$(echo  ${ProcessDetails} | jq '.[] | .processDetails[].componentID')
            environmentID=$(echo  ${ProcessDetails} | jq '.[] | .processDetails[0].environmentID')
            echo "::set-output name=componentID::$componentID"
            echo "::set-output name=environmentID::$environmentID"
            echo "::set-output name=packageVersion::$packageVersion"
            componentIdsArray=($(echo $componentID))
            output=($(
                  for i in ${componentIdsArray[@]}
                  do
                    echo -ne "'$i,"
                  done
                  ) )
                  output=${output:0:-1}
                  echo ${output//,/,}
            echo $output
            echo "::set-output name=componentID_Array::$componentIdsArray"
  
            
  createPackage:
    
    environment: Dev
    env: 
      MY_USERNAME: ${{ secrets.MY_USERNAME }}
      MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
    needs: getProcessInfo
    strategy: 
     matrix:
      componentIdArray: ${{needs.getProcessInfo.outputs.output4}}
     
    runs-on: ubuntu-latest
    outputs:
      output5: ${{ steps.response.outputs.packageId }}
    
    steps:
     - name: SetVariables
       id: showVariable
       run: |
           echo ${{matrix.componentIdArray}}
       
     
            
        
  
