name: 'example'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-array-builder
        uses: kanga333/json-array-builder@v0.1.0

        id: array
        with:
          # Using this repository as an example, the output of the command is
          # builder.ts
          # execer.ts
          # main.ts
          cmd: ls ProcessInfo
          separator: newline
    outputs:
      param: ${{ steps.array.outputs.build }}
  dynamic_matrix:
    needs:
      - matrix_input
    strategy:
      matrix:
        # Three matrix jobs work, builder.ts, execer.ts. main.ts
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.param }}
